apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: novaadc/demo-blog
        imagePullPolicy: Always
        ports:
        - containerPort: 80